// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Try2.Context;

#nullable disable

namespace Try2.Migrations
{
    [DbContext(typeof(UsersContext))]
    [Migration("20230805064422_NewMigration")]
    partial class NewMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Try2.Context.Automobile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("GosNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoadCapacity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Mileage")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Purpose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YearOfIssue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YearOfRepair")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Automobiles");
                });

            modelBuilder.Entity("Try2.Context.Bank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Banks");
                });

            modelBuilder.Entity("Try2.Context.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("Try2.Context.Cargo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<decimal>("InsuranceValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int?>("UnitId")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("UnitId");

                    b.ToTable("Cargos");
                });

            modelBuilder.Entity("Try2.Context.Checking_account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BankId")
                        .HasColumnType("int");

                    b.Property<string>("Check")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.ToTable("Checking_Accounts");
                });

            modelBuilder.Entity("Try2.Context.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Checking_AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataOfIssue")
                        .HasColumnType("datetime2");

                    b.Property<string>("Inn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPhysical")
                        .HasColumnType("bit");

                    b.Property<string>("IssuedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LegalAdress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LegalPersonName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeriesAndNumberPass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Checking_AccountId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Try2.Context.Crew", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Crews");
                });

            modelBuilder.Entity("Try2.Context.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("ClassId")
                        .HasColumnType("int");

                    b.Property<int?>("CrewId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkExperience")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("YearOfBirth")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ClassId");

                    b.HasIndex("CrewId");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("Try2.Context.DriverCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DriverCategories");
                });

            modelBuilder.Entity("Try2.Context.DriverClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DriverClasses");
                });

            modelBuilder.Entity("Try2.Context.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AutomobileId")
                        .HasColumnType("int");

                    b.Property<int?>("CrewId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AutomobileId");

                    b.HasIndex("CrewId");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("Try2.Context.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<int?>("FlightId")
                        .HasColumnType("int");

                    b.Property<string>("LoadingAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OrderCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OrderData")
                        .HasColumnType("datetime2");

                    b.Property<string>("RouteLength")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnloadingAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("FlightId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Try2.Context.Right", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("D")
                        .HasColumnType("bit");

                    b.Property<bool>("E")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("R")
                        .HasColumnType("bit");

                    b.Property<bool>("W")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Right");
                });

            modelBuilder.Entity("Try2.Context.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("Try2.Context.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RightId")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RightId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Try2.Context.Automobile", b =>
                {
                    b.HasOne("Try2.Context.Brand", "Brand")
                        .WithMany("Automobiles")
                        .HasForeignKey("BrandId");

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("Try2.Context.Cargo", b =>
                {
                    b.HasOne("Try2.Context.Order", "Order")
                        .WithMany("Cargos")
                        .HasForeignKey("OrderId");

                    b.HasOne("Try2.Context.Unit", "Unit")
                        .WithMany("Cargos")
                        .HasForeignKey("UnitId");

                    b.Navigation("Order");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Try2.Context.Checking_account", b =>
                {
                    b.HasOne("Try2.Context.Bank", "Bank")
                        .WithMany("_accounts")
                        .HasForeignKey("BankId");

                    b.Navigation("Bank");
                });

            modelBuilder.Entity("Try2.Context.Client", b =>
                {
                    b.HasOne("Try2.Context.Checking_account", "Checking_Account")
                        .WithMany("Clients")
                        .HasForeignKey("Checking_AccountId");

                    b.Navigation("Checking_Account");
                });

            modelBuilder.Entity("Try2.Context.Driver", b =>
                {
                    b.HasOne("Try2.Context.DriverCategory", "Category")
                        .WithMany("Drivers")
                        .HasForeignKey("CategoryId");

                    b.HasOne("Try2.Context.DriverClass", "Class")
                        .WithMany("Drivers")
                        .HasForeignKey("ClassId");

                    b.HasOne("Try2.Context.Crew", "Crew")
                        .WithMany("Drivers")
                        .HasForeignKey("CrewId");

                    b.Navigation("Category");

                    b.Navigation("Class");

                    b.Navigation("Crew");
                });

            modelBuilder.Entity("Try2.Context.Flight", b =>
                {
                    b.HasOne("Try2.Context.Automobile", "Automobile")
                        .WithMany("Flights")
                        .HasForeignKey("AutomobileId");

                    b.HasOne("Try2.Context.Crew", "Crew")
                        .WithMany("Flights")
                        .HasForeignKey("CrewId");

                    b.Navigation("Automobile");

                    b.Navigation("Crew");
                });

            modelBuilder.Entity("Try2.Context.Order", b =>
                {
                    b.HasOne("Try2.Context.Client", "Client")
                        .WithMany("Orders")
                        .HasForeignKey("ClientId");

                    b.HasOne("Try2.Context.Flight", "Flight")
                        .WithMany()
                        .HasForeignKey("FlightId");

                    b.Navigation("Client");

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("Try2.Context.User", b =>
                {
                    b.HasOne("Try2.Context.Right", "Right")
                        .WithMany("Users")
                        .HasForeignKey("RightId");

                    b.Navigation("Right");
                });

            modelBuilder.Entity("Try2.Context.Automobile", b =>
                {
                    b.Navigation("Flights");
                });

            modelBuilder.Entity("Try2.Context.Bank", b =>
                {
                    b.Navigation("_accounts");
                });

            modelBuilder.Entity("Try2.Context.Brand", b =>
                {
                    b.Navigation("Automobiles");
                });

            modelBuilder.Entity("Try2.Context.Checking_account", b =>
                {
                    b.Navigation("Clients");
                });

            modelBuilder.Entity("Try2.Context.Client", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Try2.Context.Crew", b =>
                {
                    b.Navigation("Drivers");

                    b.Navigation("Flights");
                });

            modelBuilder.Entity("Try2.Context.DriverCategory", b =>
                {
                    b.Navigation("Drivers");
                });

            modelBuilder.Entity("Try2.Context.DriverClass", b =>
                {
                    b.Navigation("Drivers");
                });

            modelBuilder.Entity("Try2.Context.Order", b =>
                {
                    b.Navigation("Cargos");
                });

            modelBuilder.Entity("Try2.Context.Right", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Try2.Context.Unit", b =>
                {
                    b.Navigation("Cargos");
                });
#pragma warning restore 612, 618
        }
    }
}
